class Place {
  final String title;
  final double rating;
  final String image;
  final String overview;
  final String description;
  final List<String> tags;
  final double latitude; // Ensure latitude is double
  final double longitude; // Ensure longitude is double

  Place({
    required this.title,
    required this.rating,
    required this.image,
    required this.overview,
    required this.description,
    required this.tags,
    required this.latitude,
    required this.longitude, 
  });

  get favorite => null;
  get category => null;
}

class PlaceCategory {
  final String category;
  final List<Place> places;

  PlaceCategory({
    required this.category,
    required this.places,
  });

  get name => null;
}

List<PlaceCategory> placeCategories = [
  PlaceCategory(
    category: 'Stays',
    places: [
      Place(
    title: 'Che Beach House',
    rating: 4.2,
    image: 'assets/Stays/stay1.jpg',
    overview: 'A charming beach house with stunning ocean views and serene surroundings.',
    description: 'Che Beach House is a perfect location. An absolute gem! The house is so beautiful, clean and very comfortable bed. The sea view and landscape was awesome',
    tags: ['Free Wifi', 'Pool', 'Air-conditioned', 'Friendly service', ' Beach access'],
    latitude: 5.254019756309421, 
    longitude: 103.18278020762014,
  ),
  Place(
    title: 'Sasuka Guesthouse',
    rating: 4.7,
    image: 'assets/Stays/stay2.jpg',
    overview: 'A clean guesthouse with modern amenities and friendly staff.',
    description: 'Sasuka Guesthouse provides a welcoming environment with clean, modern rooms and excellent service. The staff is known for their friendliness and willingness to help with any requests. It\'s a great choice for both short and long stays, offering convenience and comfort at an affordable price.',
    tags: ['Clean', 'Modern', 'Friendly service', 'Affordable'],
    latitude: 5.251227503077986, 
    longitude: 103.1828044852501,
  ),
  Place(
    title: 'Mini Hotel Concept',
    rating: 4.9,
    image: 'assets/Stays/stay3.jpg',
    overview: 'A unique mini hotel offering compact, yet comfortable accommodations.',
    description: 'Mini Hotel Concept offers a unique staying experience with its compact yet efficiently designed rooms. Guests appreciate the innovative use of space and the stylish decor. It\'s an excellent option for travelers looking for modern, budget-friendly accommodation without sacrificing comfort.',
    tags: ['Free Wifi', 'Comfortable', 'Modern', 'Friendly service', 'Free cancellation'],
    latitude: 5.256658741801793, 
    longitude: 103.13001527791427,
  ),
  Place(
    title: 'Zeeyad Homestay Kuala Terengganu',
    rating: 4.6,
    image: 'assets/Stays/stay4.jpg',
    overview: 'A homestay providing a clean and comfortable place to stay.',
    description: 'Zeeyad Homestay is renowned for its warm hospitality and home-like ambiance. Guests feel at home with the friendly hosts and enjoy the authentic Malaysian experience. The homestay is well-equipped with all essentials, making it a perfect choice for travelers looking for a cultural immersion.',
    tags: ['Free parking', 'Air-conditioned', 'Friendly service', 'Free cancellation'],
    latitude: 5.282989620685387, 
    longitude: 103.16077997986025,
  ),
  Place(
    title: 'Kampung Cina Hotel',
    rating: 4.7,
    image: 'assets/Stays/stay5.jpg',
    overview: 'A hotel located in the heart of Kampung Cina, offering cultural experiences.',
    description: 'Located in the vibrant area of Kampung Cina, this hotel provides easy access to local attractions and cultural sites. Guests love the blend of modern comfort and traditional charm. It\'s an ideal spot for those wanting to explore the local culture and cuisine while staying in a comfortable setting.',
    tags: [' Free Wi-Fi', 'Air-conditioned', 'Friendly service'],
    latitude: 5.334041046057535, 
    longitude: 103.13303242180397,
  ),
  Place(
    title: 'DJ Citi Plaza Hotel & Suites',
    rating: 4.9,
    image: 'assets/Stays/stay6.jpg',
    overview: 'A modern hotel with luxurious suites and excellent city views.',
    description: 'DJ Citi Plaza Hotel & Suites offers luxury accommodations with spacious rooms and top-notch amenities. Guests often rave about the stunning city views and the high level of service. It\'s perfect for both business and leisure travelers looking for a luxurious stay.',
    tags: ['Free Wi-Fi', 'Air-conditioned', 'Modern', 'High Service'],
    latitude: 5.335033093050768, 
    longitude: 103.13998811000562,
  ),
  Place(
    title: 'ISETIA HOMESTAY',
    rating: 4.8,
    image: 'assets/Stays/stay7.jpg',
    overview: 'A homestay with comfortable accommodations and easy access to local attractions.',
    description: 'ISETIA HOMESTAY provides a cozy and comfortable stay with easy access to nearby attractions. Guests enjoy the clean, well-furnished rooms and the friendly hosts who make them feel at home. It\'s a great choice for families and solo travelers alike.',
    tags: ['Free Wi-Fi', 'Pool', 'Friendly service', ' Air-conditioned', 'Modern'],
    latitude: 5.269413313101879, 
    longitude: 103.1737002551031,
  ),
  Place(
    title: 'Double H Boutique Hotel',
    rating: 4.7,
    image: 'assets/Stays/stay8.jpg',
    overview: 'A boutique hotel offering stylish rooms and personalized services.',
    description: 'Double H Boutique Hotel stands out for its stylish and well-decorated rooms. The personalized service and attention to detail make it a favorite among guests. It\'s perfect for travelers looking for a unique and upscale accommodation experience.',
    tags: ['Free Wi-Fi', 'Air-conditioned', 'Modern'],
    latitude: 5.356314014732294, 
    longitude: 103.09651075205477,
  ),
  Place(
    title: 'Leisure Lodge',
    rating: 4.5,
    image: 'assets/Stays/stay9.jpg',
    overview: 'A lodge perfect for leisure travelers, offering a relaxing environment.',
    description: 'Leisure Lodge is ideal for those looking to relax and unwind. The tranquil setting and comfortable accommodations make it a popular choice for leisure travelers. Guests appreciate the serene environment and the friendly staff who go out of their way to ensure a pleasant stay.',
    tags: ['Free Wi-Fi', 'Air-conditioned', 'Comfortable', 'Friendly service'],
    latitude: 5.329038815834489, 
    longitude: 103.1355108955488,
  ),
  Place(
    title: 'The Payang Hotel',
    rating: 4.5,
    image: 'assets/Stays/stay10.jpg',
    overview: 'A hotel providing comfortable accommodations and convenient access to the city.',
    description: 'The Payang Hotel offers convenience and comfort with its well-appointed rooms and central location. Guests enjoy the easy access to city attractions and the comfortable stay. It\'s a great choice for business travelers and tourists alike.',
    tags: ['Modern', 'Comfortable', 'Air-conditioned', 'High Service'],
    latitude: 5.334930649161033, 
    longitude: 103.13486161146633,
  ),
  Place(
    title: 'HOMESTAY CAMELIA KUALA TERENGGANU',
    rating: 4.9,
    image: 'assets/Stays/stay11.jpg',
    overview: 'A homestay offering a homely atmosphere and excellent hospitality.',
    description: 'Homestay Camelia Kuala Terengganu is known for its warm and welcoming environment. The hosts provide excellent hospitality, making guests feel right at home. It\'s a top choice for those looking for a homely stay with all the necessary amenities.',
    tags: ['Free Wi-Fi', 'Friendly service', 'Comfortable'],
    latitude: 5.3289793481845145, 
    longitude: 103.14804177339367,
  ),
  Place(
    title: 'Avohomestay',
    rating: 4.8,
    image: 'assets/Stays/stay12.jpg',
    overview: 'A cozy homestay with modern amenities and a friendly host.',
    description: 'Avohomestay offers a comfortable and cozy stay with modern amenities. Guests appreciate the cleanliness and the friendly host who ensures a pleasant stay. It\'s perfect for travelers looking for a homely and comfortable environment.',
    tags: ['Free Wi-Fi', 'Air-conditioned', 'Clean', 'Friendly service'],
    latitude: 5.26473834445809, 
    longitude: 103.11420508647662,
  ),
  Place(
    title: 'Homestay Camelia Kuala Terengganu 2 - Orkid House',
    rating: 4.9,
    image: 'assets/Stays/stay13.jpg',
    overview: 'A homestay with a beautiful garden and traditional decor.',
    description: 'Orkid House provides a beautiful and serene environment with its traditional decor and lovely garden. Guests enjoy the peaceful setting and the excellent hospitality. It\'s an ideal choice for those wanting a traditional and comfortable stay.',
    tags: ['Clean', 'Friendly service', 'Comfortable', 'Affordable'],
    latitude: 5.348763347337619, 
    longitude: 103.12856238999623,
  ),
  Place(
    title: 'Kapas Kemuning Inn Kuala Terengganu',
    rating: 4.6,
    image: 'assets/Stays/stay14.jpg',
    overview: 'An inn offering comfortable accommodations and a tranquil setting.',
    description: 'Kapas Kemuning Inn is perfect for travelers seeking a tranquil and comfortable stay. The inn offers well-furnished rooms and a peaceful environment, making it a great choice for relaxation. Guests often praise the friendly staff and the serene setting.',
    tags: ['Affordable', 'Comfortable', 'Strategic'],
    latitude: 5.313206778801274, 
    longitude: 103.14163687433778,
  ),
  Place(
    title: 'Homestay Che Yang',
    rating: 4.7,
    image: 'assets/Stays/stay15.jpg',
    overview: 'A homestay providing a warm and welcoming environment.',
    description: 'Homestay Che Yang is known for its warm hospitality and comfortable accommodations. Guests feel welcomed and at home, enjoying the clean and well-maintained rooms. It\'s an excellent choice for families and solo travelers.',
    tags: ['Free Wi-Fi', 'Air-conditioned', 'Strategic', 'Friendly service'],
    latitude: 5.287211017939135, 
    longitude: 103.10016435615461,
  ),
  Place(
    title: 'GADING CHALET',
    rating: 4.8,
    image: 'assets/Stays/stay16.jpg',
    overview: 'A chalet with rustic charm and modern amenities.',
    description: 'Gading Chalet offers a unique stay with its rustic charm and modern amenities. Guests enjoy the cozy atmosphere and the well-equipped rooms. It\'s a perfect getaway for those looking to experience nature with all the comforts of home.',
    tags: ['Affordable', 'Comfortable', 'Friendly service'],
    latitude: 5.33807635453045, 
    longitude: 103.08536970492966
  ),
  Place(
    title: 'Jen Homestay',
    rating: 4.6,
    image: 'assets/Stays/stay17.jpg',
    overview: 'A homestay with comfortable accommodations and friendly service.',
    description: 'Jen Homestay provides a comfortable and welcoming environment with excellent service. The rooms are clean and well-furnished, and the hosts are known for their hospitality. It\'s a great option for travelers looking for a homely stay.',
    tags: ['Comfortable', 'Friendly service', 'Clean', 'Free Wi-Fi'],
    latitude: 5.3322039531387375, 
    longitude: 103.13466353709171,
  ),
  Place(
    title: 'Bradong Homestay',
    rating: 5.0,
    image: 'assets/Stays/stay18.jpg',
    overview: 'A homestay offering top-notch amenities and excellent service.',
    description: 'Bradong Homestay is highly rated for its exceptional service and top-notch amenities. Guests appreciate the attention to detail and the luxurious accommodations. It\'s a top choice for those looking for a high-quality stay.',
    tags: ['Free Wi-Fi', 'Pool', 'Modern', 'Air-conditioned'],
    latitude: 5.334655533066126, 
    longitude: 103.14776128129331,
  ),
  Place(
    title: 'Aaeesha Homestay & Roomstay',
    rating: 4.6,
    image: 'assets/Stays/stay19.jpg',
    overview: 'A homestay with comfortable rooms and a friendly host.',
    description: 'Aaeesha Homestay & Roomstay offers a comfortable stay with well-maintained rooms and a friendly host. Guests feel welcomed and enjoy the cozy environment. It\'s a great option for those looking for a simple yet comfortable stay.',
    tags: ['Comfortable', 'Friendly service', 'Clean', 'Affordable'],
    latitude: 5.394582046570937, 
    longitude: 103.08317975144223,
  ),
  Place(
    title: 'The Grand Puteri Hotel',
    rating: 4.0,
    image: 'assets/Stays/stay20.jpg',
    overview: 'A grand hotel offering luxurious accommodations and excellent facilities.',
    description: 'The Grand Puteri Hotel provides luxurious accommodations with excellent facilities. Guests appreciate the spacious rooms and the high level of service. It\'s an ideal choice for those looking for a grand and comfortable stay.',
    tags: ['Free Wi-Fi', 'Air-conditioned', 'Pool', 'High Service', 'Comfortable'],
    latitude: 5.3329585031445434, 
    longitude: 103.13807555107209,
  ),
    ],
  ),
  PlaceCategory(
    category: 'Shops',
    places: [
      Place(
  title: 'Kompleks Paya Bunga Square',
  rating: 4.2,
  image: 'assets/Shops/shop1.jpg',
  overview: 'Integrated development which includes shopping centre, office space and a hotel.',
  description: 'An integrated development with a four-storey mall with UTC offices to make it easy for any government transactions to be made.',
  tags: ['Bowling', 'Cinema', 'Government', 'UTC', 'Popular'],
  latitude: 5.331030364606831, 
    longitude: 103.13668065434348,
),
Place(
  title: 'Mayang Mall',
  rating: 2.5,
  image: 'assets/Shops/shop2.jpg',
  overview: 'A new lifestyle mall',
  description: 'Mayang Mall serve as a food haven for all food lovers, as well as a hip, insta-ready hangout spot perfect for friends and family gatherings. ',
  tags: ['Shopping', 'Food Court', 'Entertainment', 'New'],
  latitude: 5.33722289794797, 
    longitude: 103.14448793808133,
),
Place(
  title: 'Mydin Mall Kuala Terengganu',
  rating: 4.1,
  image: 'assets/Shops/shop3.jpg',
  overview: 'A mall that offers a diverse range of retail outlets, dining options, and entertainment facilities.',
  description: 'Mydin Mall Kuala Terengganu stands as a vibrant commercial hub, featuring an extensive variety of stores that cater to all shopping needs, from fashion and electronics to groceries and home goods.',
  tags: ['Arcade', 'Electronics', 'Groceries', 'Food Court'],
  latitude: 5.311279736128688, 
    longitude: 103.1305876604792,
),
Place(
  title: 'PASAR PAYANG',
  rating: 4.3,
  image: 'assets/Shops/shop4.jpg',
  overview: 'Known for its wide array of goods ranging from fresh produce and traditional crafts to clothing and souvenirs.',
  description: 'Pasar Payang Kuala Terengganu is a lively marketplace that captures the essence of local culture and commerce. Visitors can wander through the maze of stalls, discovering an assortment of fresh fruits, vegetables, and seafood, as well as traditional Malay delicacies and snacks.',
  tags: ['Cloths', 'Food Court', 'Groceries', 'Souvenirs'],
  latitude: 5.337107711597264, 
    longitude: 103.13620505641744,
),
Place(
  title: 'Paya Bunga Sentral',
  rating: 4.0,
  image: 'assets/Shops/shop5.jpg',
  overview: 'A dynamic and multifaceted complex situated in Kuala Terengganu, combining entertainment, retail, and administrative functions. ',
  description: 'Paya Bunga Sentral in Kuala Terengganu is a versatile and bustling center that caters to a variety of interests and needs. The complex features a state-of-the-art bowling alley, offering a fun and engaging activity for families, friends, and bowling enthusiasts.',
  tags: ['Bowling', 'Cinema', 'Government'],
  latitude: 5.330379071122721, 
    longitude: 103.1368490214956,
),
Place(
  title: 'Creative101',
  rating: 5.0,
  image: 'assets/Shops/shop6.jpg',
  overview: 'A vibrant and imaginative store that caters to a wide range of creative needs, offering printing services, kid toys, stickers, and stamps',
  description: 'Creative101 is a haven for creativity and fun, providing a diverse array of products and services that inspire imagination and play. The store is well-known for its high-quality printing services, ideal for both personal and professional projects, ensuring vibrant and precise results every time.',
  tags: ['Printing', 'Kid Toys', 'Sticker', 'Stamp'],
  latitude: 5.3331176394259865, 
    longitude: 103.15044802639726,
),
Place(
  title: 'Paya Bunga Plaza',
  rating: 3.7,
  image: 'assets/Shops/shop7.jpg',
  overview: 'A well-loved for its diverse selection of stores, groceries, fresh products, and essential items, making it a convenient one-stop shop for the community',
  description: 'Paya Bunga Plaza stands out as a bustling commercial hub that meets the varied needs of its visitors. Shoppers can explore a wide array of retail stores, from fashion boutiques to electronics shops, providing a diverse shopping experience.',
  tags: ['Shopping', 'Groceries', 'Fresh Products', 'Basic Needs', 'Electronics'],
  latitude: 5.331110619830452, 
    longitude: 103.13789599474543,
),
Place(
  title: 'Bazaar Warisan',
  rating: 3.5,
  image: 'assets/Shops/shop8.jpg',
  overview: 'A popular destination for both locals and tourists seeking to explore and purchase traditional Malaysian crafts and textiles.',
  description: 'Bazaar Warisan is a treasure trove of traditional Malaysian crafts and textiles, offering a vibrant and immersive shopping experience. The market is famous for its wide variety of souvenirs, perfect for visitors looking to take home a piece of local culture. ',
  tags: ['Souvenirs', 'Batik', 'Songket', 'Cloths', 'Silks'],
  latitude: 5.335777808093622, 
    longitude: 103.13588161342888,
),
Place(
  title: 'F.O.S KTCC Mall',
  rating: 3.7,
  image: 'assets/Shops/shop9.jpg',
  overview: 'A popular retail destination known for its wide selection of affordable and stylish clothing for both men and women',
  description: 'F.O.S KTCC Mall is a go-to store for fashion enthusiasts seeking a diverse range of clothing options. The store features a vast collection of stylish and affordable outfits for both females and males, ensuring that every shopper finds something to suit their taste and budget.',
  tags: ['Cloths', 'Female Outfit', 'Male Outfit'],
  latitude: 5.333154556593954, 
    longitude: 103.15000139033866,
),
Place(
  title: 'Pacific',
  rating: 4.2,
  image: 'assets/Shops/shop10.jpg',
  overview: 'A versatile shopping venue known for its comprehensive grocery section, various stalls, and a wide selection of clothing.',
  description: 'Pacific offers a dynamic shopping experience, catering to a wide range of customer needs. The grocery section is well-stocked with a variety of fresh produce, household essentials, and everyday necessities, ensuring that shoppers can find everything they need for their daily lives.',
  tags: ['Grocery', 'Stalls', 'Cloths'],
  latitude: 5.333043856084659, 
    longitude: 103.15049141011134,
),
Place(
  title: 'One Jeans Store',
  rating: 4.1,
  image: 'assets/Shops/shop11.jpg',
  overview: 'A specialized retail outlet known for its extensive range of jeans, clothing, and shoes, particularly catering to male fashion.',
  description: 'One Jeans Store stands out as a premier destination for denim enthusiasts and fashion-conscious shoppers. The store boasts an impressive collection of jeans in various styles, cuts, and washes, ensuring that every customer finds the perfect pair to suit their taste and fit.',
  tags: ['Cloths', 'Shoes', 'Male Outfit'],
  latitude: 5.310826219458079, 
    longitude: 103.12914594576979,
),
Place(
  title: 'MurohbohExclusive',
  rating: 4.9,
  image: 'assets/Shops/shop12.jpg',
  overview: 'A distinguished boutique, celebrated for its exquisite collection of batik, high-quality cloth, and fashionable outfits for both females and males',
  description: 'Murohboh Exclusive offers a sophisticated shopping experience, specializing in beautifully crafted batik and premium cloth. The boutique is renowned for its wide selection of stylish female outfits, including dresses, blouses, and traditional wear, designed to showcase the intricate patterns and vibrant colors of batik.',
  tags: ['Batik', 'Cloth', 'Female Outfit', 'Male Outfit'],
  latitude: 5.302133699666269, 
    longitude: 103.12108873860738,
),
Place(
  title: 'Giant Kuala Terengganu',
  rating: 4.1,
  image: 'assets/Shops/shop13.jpg',
  overview: ' A prominent hypermarket known for its extensive range of groceries, basic needs, fresh products, and electronics.',
  description: 'Giant Kuala Terengganu is a well-established hypermarket that provides a comprehensive shopping experience, catering to a broad spectrum of customer needs. The grocery section is expansive, featuring a diverse array of fresh products, including fruits, vegetables, meats, and dairy, ensuring that customers have access to high-quality ingredients for their daily meals',
  tags: ['Grocery', 'Basic Needs', 'Fresh Products', 'Electronics'],
  latitude: 5.3108996569302676, 
    longitude: 103.12843465866268,
),
Place(
  title: 'Econsave Kuala Terengganu',
  rating: 4.1,
  image: 'assets/Shops/shop14.jpg',
  overview: 'A popular hypermarket renowned for its diverse selection of groceries, fresh products, electronics, and clothing.',
  description: 'Econsave Kuala Terengganu stands out as a versatile and well-stocked hypermarket that caters to a variety of shopping needs. The grocery section is abundant with a wide array of fresh products, including fruits, vegetables, meats, and dairy, ensuring that customers can find high-quality ingredients for their daily meals. ',
  tags: ['Grocery', 'Fresh Products', 'Electronics', 'Cloth'],
  latitude: 5.337286595334131, 
    longitude: 103.1414181937487,
),
Place(
  title: 'Jakel',
  rating: 4.0,
  image: 'assets/Shops/shop15.jpg',
  overview: 'A premier retail store known for its extensive collection of high-quality cloth and fashionable outfits for both females and males.',
  description: 'Jakel offers a luxurious shopping experience with its wide selection of premium cloth and ready-to-wear outfits. The store is renowned for its high-quality fabrics, which are perfect for tailoring bespoke clothing. Female shoppers can explore an array of stylish outfits, including elegant dresses, traditional wear, and contemporary fashion, all designed to highlight the beauty and sophistication of the wearer.',
  tags: ['Cloth', 'Female Outfit', 'Male Outfit'],
  latitude: 5.357435675162253, 
    longitude: 103.09479041787795,
),
Place(
  title: 'Jeane Collection Kuala Terengganu',
  rating: 5.0,
  image: 'assets/Shops/shop16.jpg',
  overview: 'A well-loved boutique specializing in stylish female outfits and high-quality cloth.',
  description: 'Jeane Collection Kuala Terengganu offers a chic and fashionable shopping experience, catering specifically to female shoppers. The boutique features an impressive selection of trendy and sophisticated female outfits, ranging from casual wear to elegant dresses and traditional attire. ',
  tags: ['Female outfit', 'Cloth'],
  latitude: 5.3305755796347, 
    longitude: 103.14427397736624,
),
Place(
  title: 'NACC Batik Pavilion',
  rating: 4.4,
  image: 'assets/Shops/shop17.jpg',
  overview: 'A distinguished boutique renowned for its exquisite collection of batik, high-quality cloth, and luxurious silk',
  description: 'NACC Batik Pavilion in Kuala Terengganu offers an enchanting shopping experience with its curated selection of traditional and contemporary batik designs. The boutique is celebrated for its high-quality cloth, featuring intricate patterns and vibrant colors that showcase the rich heritage of Malaysian textile artistry.',
  tags: ['Batik', 'Cloth', 'Silk'],
  latitude: 5.276362817982973, 
    longitude: 103.16725713914927,
),
Place(
  title: '269 Streetwear',
  rating: 3.9,
  image: 'assets/Shops/shop18.jpg',
  overview: 'A trendy retail store known for its stylish collection of cloth, male outfits, caps, and jeans.',
  description: '269 Streetwear in Kuala Terengganu offers a modern and edgy shopping experience, catering to the fashion needs of young and stylish men. The store features a wide range of male outfits, from casual streetwear to trendy formal attire, ensuring that every customer finds something to suit their personal style.',
  tags: ['Cloth', 'Male Outfit', 'Caps', 'Jeans'],
  latitude: 5.336405256758452, 
    longitude: 103.14368975249405,
),
Place(
  title: 'Noor Arfa Batek Sdn. Bhd.',
  rating: 4.1,
  image: 'assets/Shops/shop19.jpg',
  overview: 'A must-visit destination for those seeking authentic and beautifully crafted Malaysian textiles.',
  description: 'Noor Arfa Batek Sdn. Bhd. offers a rich and immersive shopping experience, showcasing the finest batik art and textiles in Kuala Terengganu. The boutique is famed for its intricate and vibrant batik designs, which highlight the exceptional craftsmanship and cultural heritage of Malaysia.',
  tags: ['Batik', 'Cloth', 'Female Outfit', 'Male Outfit'],
  latitude: 5.276378445614737, 
    longitude: -103.16728664843278,
),
Place(
  title: '7 Rex Trading Sdn Bhd',
  rating: 4.3,
  image: 'assets/Shops/shop20.jpg',
  overview: 'A versatile retail store in Kuala Terengganu, known for its extensive range of school uniforms, high-quality cloth, and accessories.',
  description: '7 Rex Trading Sdn Bhd offers a comprehensive shopping experience with a focus on quality and customer satisfaction. The store is particularly renowned for its wide selection of school uniforms, which are made from durable fabrics to ensure comfort and longevity for students.',
  tags: ['School Uniform', 'Cloth', 'Accesories'],
  latitude: 5.33516533729135, 
    longitude: 103.13929024743891,
),
    ],
  ),
  PlaceCategory(
    category: 'Historical Sites',
    places: [
      Place(
    title: 'Makam DiRaja Bukit Keledang',
    rating: 4.1,
    image: 'assets/HistoricalSites/history1.jpg',
    overview: 'Explore the remnants of ancient civilizations.',
    description: 'These ancient ruins offer a glimpse into the lives of people who lived thousands of years ago. The site is well-preserved and offers guided tours to enhance your experience.',
    tags: ['Ancient', 'Heritage', 'Guided Tours', 'Cultural'],
    latitude: 5.330203701946612, 
    longitude: 103.1333650461007,
  ),
  Place(
    title: 'Ho Ann Kiong Temple',
    rating: 4.4,
    image: 'assets/HistoricalSites/history2.jpg',
    overview: 'A well-preserved castle from the medieval era.',
    description: 'This medieval castle stands tall with its impressive architecture and rich history. Visitors can explore the castle grounds and learn about its historical significance through informative displays and tours.',
    tags: ['Medieval', 'Architecture', 'Educational Tours', 'Castle'],
    latitude: 5.332750487121346, 
    longitude: 103.13286530010099
  ),
  Place(
    title: 'Kuala Terengganu Turtle Sculpture',
    rating: 4.0,
    image: 'assets/HistoricalSites/history3.jpg',
    overview: 'A museum showcasing historical artifacts and exhibits.',
    description: 'The historical museum houses a vast collection of artifacts and exhibits that tell the story of the region\'s past. It is a great place for history enthusiasts and offers educational programs for all ages.',
    tags: ['Artifacts', 'Museum', 'Family-friendly', 'Educational'],
    latitude: 5.33202700135615, 
    longitude: 103.1326845983484,
  ),
  Place(
    title: 'Istana Maziah',
    rating: 4.4,
    image: 'assets/HistoricalSites/history4.jpg',
    overview: 'A historical battlefield where significant battles were fought.',
    description: 'This battlefield is a poignant reminder of the conflicts that shaped the nation. Visitors can walk the grounds and read about the key events and figures involved in the battles.',
    tags: ['Battlefield', 'War Memorial', 'Educational', 'History'],
    latitude: 5.336583725403609, 
    longitude: 103.13795073203674,
  ),
  Place(
    title: 'Turtle Alley',
    rating: 4.2,
    image: 'assets/HistoricalSites/history5.jpg',
    overview: 'A monument commemorating a significant historical event.',
    description: 'This historical monument stands as a tribute to an important event in history. It is a place of reflection and remembrance, with plaques and inscriptions detailing the event\'s significance.',
    tags: ['Monument', 'Reflection', 'Cultural', 'Tribute'],
    latitude: 5.33207306220926, 
    longitude: 103.13204514136861,
  ),
  Place(
    title: 'Thean Hou Temple',
    rating: 4.4,
    image: 'assets/HistoricalSites/history6.jpg',
    overview: 'An active archaeological site with ongoing excavations.',
    description: 'The archaeological site is an exciting place where discoveries are still being made. Visitors can see archaeologists at work and learn about the methods used to uncover the past.',
    tags: ['Archaeology', 'Excavations', 'Discovery', 'Educational'],
    latitude: 5.3302287329343345, 
    longitude: 103.13266039434775,
  ),
  Place(
    title: 'Bulatan Batu Bersurat Kuala Terengganu',
    rating: 4.3,
    image: 'assets/HistoricalSites/history7.jpg',
    overview: 'A beautiful church with historical and architectural significance.',
    description: 'This historic church is a marvel of architecture and a testament to the craftsmanship of its builders. It has been a place of worship for centuries and is open to visitors for tours and services.',
    tags: ['Church', 'Architecture', 'Cultural Tours', 'Historic'],
    latitude: 5.328782327422513, 
    longitude: 103.14613138035567,
  ),
  Place(
    title: 'Masjid Abidin Masjid Negeri Terengganu',
    rating: 4.7,
    image: 'assets/HistoricalSites/history8.jpg',
    overview: 'A temple from ancient times, still in use today.',
    description: 'The ancient temple is a sacred site that has been in continuous use for thousands of years. It is a place of spiritual significance and offers a glimpse into ancient religious practices.',
    tags: ['Temple', 'Spiritual', 'Ancient', 'Religious Practices'],
    latitude: 5.3342716830620605, 
    longitude: 103.13811398666348,
  ),
  Place(
    title: 'Istana Nur Nadhirah',
    rating: 4.4,
    image: 'assets/HistoricalSites/history9.jpg',
    overview: 'The site of a historic battle that changed the course of history.',
    description: 'This historic battlefield is a somber reminder of the past conflicts. Visitors can learn about the strategies and outcomes of the battle through informative displays and guided tours.',
    tags: ['Battlefield', 'Historic', 'Guided Tours', 'Conflict History'],
    latitude: 5.320527705050817, 
    longitude: 103.15297306140695,
  ),
  Place(
    title: 'Payang Memory Lane',
    rating: 4.1,
    image: 'assets/HistoricalSites/history10.jpg',
    overview: 'A preserved colonial settlement with original buildings.',
    description: 'The colonial settlement offers a look at life during the colonial period. The original buildings have been preserved, and reenactments and exhibits bring history to life for visitors.',
    tags: ['Colonial', 'Reenactments', 'Cultural Exhibits', 'Heritage'],
    latitude: 5.334955497241124, 
    longitude: 103.13490379050138,
  ),
  Place(
    title: 'Kota Lama Duyung',
    rating: 4.1,
    image: 'assets/HistoricalSites/history11.jpg',
    overview: 'A library housing rare historical books and manuscripts.',
    description: 'The historical library is a treasure trove of rare books and manuscripts. It is a quiet place for study and reflection, offering insights into the intellectual history of the region.',
    tags: ['Library', 'Rare Books', 'Manuscripts', 'Study'],
    latitude: 5.336423560726246, 
    longitude: 103.12713657807612,
  ),
  Place(
    title: 'Terengganu State Museum',
    rating: 4.4,
    image: 'assets/HistoricalSites/history12.jpg',
    overview: 'An old bridge with historical and architectural significance.',
    description: 'This historic bridge is an engineering marvel from a bygone era. It has stood the test of time and remains a functional piece of infrastructure and a tourist attraction.',
    tags: ['Bridge', 'Engineering', 'Tourist Attraction', 'Architecture'],
    latitude: 5.3187669435166285, 
    longitude: 103.10289090327187,
  ),
  Place(
    title: 'Pengkalan Perahu Petai Bubus',
    rating: 4.6,
    image: 'assets/HistoricalSites/history13.jpg',
    overview: 'A fort that played a key role in historical conflicts.',
    description: 'The historical fort is a well-preserved military structure that offers a glimpse into the past. It played a crucial role in historical conflicts and now serves as a museum and tourist attraction.',
    tags: ['Fort', 'Military', 'Conflicts', 'Museum'],
    latitude: 5.341749229792143, 
    longitude: 103.07976317542257,
  ),
  Place(
    title: 'Taman Monumen',
    rating: 4.4,
    image: 'assets/HistoricalSites/history14.jpg',
    overview: 'A town square that has been the center of community life for centuries.',
    description: 'The historic town square is a bustling place with shops, cafes, and historic buildings. It has been the heart of the community for centuries and is a great place to experience local culture.',
    tags: ['Square', 'Community', 'Historic Buildings', 'Local Culture'],
    latitude: 5.32195380279695, 
    longitude: 103.11671939097347,
  ),
  Place(
    title: 'Jambatan Angkat Kuala Terengganu',
    rating: 4.6,
    image: 'assets/HistoricalSites/history15.jpg',
    overview: 'A lighthouse that has guided ships for over a century.',
    description: 'The historic lighthouse is an iconic structure that has guided ships safely to shore for over a century. Visitors can climb to the top for a stunning view of the coastline.',
    tags: ['Lighthouse', 'Guidance', 'Iconic', 'View'],
    latitude: 5.339743664263782, 
    longitude: 103.14535383681036,
  ),
  Place(
    title: 'Taman Tamadun Islam',
    rating: 4.1,
    image: 'assets/HistoricalSites/history16.jpg',
    overview: 'A historic mill that played a vital role in local industry.',
    description: 'The historic mill is a fascinating site that showcases the importance of milling in the local industry. Visitors can see the machinery in action and learn about the milling process.',
    tags: ['Mill', 'Industry', 'Machinery', 'Educational'],
    latitude: 5.321968363482537, 
    longitude: 103.11675504805825,
  ),
  Place(
    title: 'Pusat Sains & Kreativiti Terengganu',
    rating: 4.4,
    image: 'assets/HistoricalSites/history17.jpg',
    overview: 'A historic plaza that has been a gathering place for generations.',
    description: 'The historical plaza is a vibrant place that has been a central gathering spot for generations. It is surrounded by historic buildings and offers a lively atmosphere with events and markets.',
    tags: ['Plaza', 'Gathering', 'Events', 'Historic Buildings'],
    latitude: 5.269737473608821, 
    longitude: 103.1517983677969,
  ),
  Place(
    title: 'Masjid Kristal',
    rating: 4.3,
    image: 'assets/HistoricalSites/history18.jpg',
    overview: 'A museum dedicated to preserving and presenting local history.',
    description: 'The historic museum is a comprehensive resource for understanding the local history. It features exhibits on various aspects of life in the past and offers educational programs for all ages.',
    tags: ['Museum', 'History', 'Exhibits', 'Educational'],
    latitude: 5.322307134296453, 
    longitude: 103.1206593021297
  ),
  Place(
    title: 'Pura Tanjung Sabtu',
    rating: 3.9,
    image: 'assets/HistoricalSites/history19.jpg',
    overview: 'A grand mansion with a rich history and beautiful architecture.',
    description: 'The historical mansion is a stunning example of period architecture. It has been preserved with its original furnishings and offers tours that highlight its historical significance.',
    tags: ['Mansion', 'Architecture', 'Tours', 'Heritage'],
    latitude: 5.34890704429663, 
    longitude: 103.06767735585191,
  ),
  Place(
    title: 'Istana Syarqiyyah',
    rating: 4.6,
    image: 'assets/HistoricalSites/history20.jpg',
    overview: 'A theater that has hosted performances for over a century.',
    description: 'The historic theater is a cultural landmark that has hosted performances for over a century. It has been beautifully restored and continues to be a venue for arts and entertainment.',
    tags: ['Theater', 'Performances', 'Cultural', 'Arts'],
    latitude: 5.256932000360786, 
    longitude: 103.16916835970669,
  ),
    ],
  ),
  PlaceCategory(
    category: 'Food',
    places: [
      Place(
    title: 'KBB Burger & Steak Terengganu',
    rating: 4.9,
    image: 'assets/Foods/food1.jpg',
    overview: 'Delicious burgers and steaks cooked to perfection.',
    description: 'KBB Burger & Steak is known for its mouth-watering burgers and perfectly cooked steaks. The cozy atmosphere and friendly service make it a favorite among locals and tourists alike.',
    tags: ['Burgers', 'Steaks', 'Cozy', 'Friendly Service', 'Delicious'],
    latitude: 5.337162752754992, 
    longitude: 103.14210515400242,
  ),
  Place(
    title: 'Qweens Diner',
    rating: 4.6,
    image: 'assets/Foods/food2.jpg',
    overview: 'A retro diner serving classic American dishes.',
    description: 'Qweens Diner offers a nostalgic dining experience with its retro decor and classic American dishes. The menu features a variety of comfort foods, from burgers to milkshakes.',
    tags: ['Retro', 'American', 'Comfort Food', 'Nostalgic'],
    latitude: 5.392692533773845, 
    longitude: 103.10851273740639,
  ),
  Place(
    title: 'Oishi Wowo Cafe',
    rating: 4.8,
    image: 'assets/Foods/food3.jpg',
    overview: 'A Japanese cafe with a variety of sushi and ramen.',
    description: 'Oishi Wowo Cafe brings the flavors of Japan to Terengganu with its delicious sushi and ramen dishes. The modern decor and attentive service add to the dining experience.',
    tags: ['Japanese', 'Sushi', 'Ramen', 'Modern Decor', 'Attentive Service'],
    latitude: 5.354462378968441, 
    longitude: 103.08569514104559,
  ),
  Place(
    title: 'Restoran Gossip Kitchen',
    rating: 4.3,
    image: 'assets/Foods/food4.jpg',
    overview: 'A family-friendly restaurant with a diverse menu.',
    description: 'Restoran Gossip Kitchen is a popular spot for families, offering a diverse menu that caters to all tastes. The friendly atmosphere and delicious food make it a great choice for any occasion.',
    tags: ['Family', 'Diverse Menu', 'Friendly Atmosphere', 'Delicious'],
    latitude: 5.329755806309997, 
    longitude: 103.13652624900378,
  ),
  Place(
    title: 'D Tunggal Seafood',
    rating: 3.9,
    image: 'assets/Foods/food5.jpg',
    overview: 'Fresh seafood dishes in a casual setting.',
    description: 'D Tunggal Seafood is known for its fresh seafood dishes, served in a casual and relaxed setting. The menu features a variety of options, from grilled fish to seafood platters.',
    tags: ['Seafood', 'Casual', 'Fresh', 'Grilled Fish'],
    latitude: 5.343286332300857, 
    longitude: 103.1019273815353,
  ),
  Place(
    title: 'NR Cafe',
    rating: 3.6,
    image: 'assets/Foods/food6.jpg',
    overview: 'A cozy cafe with a selection of local and international dishes.',
    description: 'NR Cafe offers a cozy dining experience with a menu that includes both local and international dishes. The relaxed atmosphere and friendly service make it a great spot to unwind.',
    tags: ['Cozy', 'Local Dishes', 'International', 'Relaxed Atmosphere'],
    latitude: 5.386364743401765, 
    longitude: 103.10002979881112,
  ),
  Place(
    title: 'Thai BBQ Seafood',
    rating: 4.6,
    image: 'assets/Foods/food7.jpg',
    overview: 'Authentic Thai BBQ and seafood dishes.',
    description: 'Thai BBQ Seafood brings the flavors of Thailand to Terengganu with its authentic BBQ and seafood dishes. The vibrant decor and lively atmosphere make it a popular choice for dining out.',
    tags: ['Thai', 'BBQ', 'Seafood', 'Lively Atmosphere'],
    latitude: 5.334101728196194, 
    longitude: 103.13228102174877,
  ),
  Place(
    title: 'Restoran Aroma Arab Global Kuala Terengganu',
    rating: 4.3,
    image: 'assets/Foods/food8.jpg',
    overview: 'A restaurant offering a taste of Arabian cuisine.',
    description: 'Restoran Aroma Arab Global serves a variety of Arabian dishes, from kebabs to hummus. The rich flavors and exotic spices provide a unique dining experience.',
    tags: ['Arabian', 'Kebabs', 'Hummus', 'Exotic Spices'],
    latitude: 5.33127497401379, 
    longitude: 103.14395145756161,
  ),
  Place(
    title: 'Restoran Ikhwan Kuala Terengganu',
    rating: 4.0,
    image: 'assets/Foods/food9.jpg',
    overview: 'A halal restaurant with a variety of local dishes.',
    description: 'Restoran Ikhwan offers a wide range of halal dishes, featuring local flavors and ingredients. The welcoming atmosphere and delicious food make it a favorite among locals.',
    tags: ['Halal', 'Local Dishes', 'Welcoming', 'Delicious Food', 'Popular'],
    latitude: 5.33570169734076, 
    longitude: 103.14524224310125,
  ),
  Place(
    title: 'The Syrup VS Soda',
    rating: 4.1,
    image: 'assets/Foods/food10.jpg',
    overview: 'A cafe specializing in unique beverages and desserts.',
    description: 'The Syrup VS Soda is known for its creative beverages and delicious desserts. The menu includes a variety of unique drinks and sweet treats, perfect for a relaxing afternoon.',
    tags: ['Beverages', 'Desserts', 'Creative Drinks', 'Sweet Treats'],
    latitude: 5.328793966752569, 
    longitude: 103.1369276251667,
  ),
  Place(
    title: 'One Cafe',
    rating: 4.4,
    image: 'assets/Foods/food11.jpg',
    overview: 'A modern cafe with a diverse menu.',
    description: 'One Cafe offers a modern dining experience with a menu that features a variety of dishes, from salads to pastas. The stylish decor and friendly service make it a great spot for dining out.',
    tags: ['Modern', 'Diverse Menu', 'Stylish Decor', 'Friendly Service', 'Variety'],
    latitude: 5.316521069536159, 
    longitude: 103.15101567728948,
  ),
  Place(
    title: 'Uncle Man Seafood Restaurant',
    rating: 5.0,
    image: 'assets/Foods/food12.jpg',
    overview: 'A seafood restaurant known for its fresh and flavorful dishes.',
    description: 'Uncle Man Seafood Restaurant is highly rated for its fresh and flavorful seafood dishes. The relaxed atmosphere and excellent service make it a top choice for seafood lovers.',
    tags: ['Seafood', 'Fresh', 'Flavorful', 'Relaxed Atmosphere', 'Top Choice'],
    latitude: 5.265603315267072, 
    longitude: 103.16935836934469,
  ),
  Place(
    title: 'Zideen Fastfood House',
    rating: 4.6,
    image: 'assets/Foods/food13.jpg',
    overview: 'A fast food restaurant with a variety of quick and tasty options.',
    description: 'Zideen Fastfood House offers a range of quick and tasty fast food options, from burgers to fried chicken. The friendly service and convenient location make it a popular choice for a quick meal.',
    tags: ['Fast Food', 'Burgers', 'Fried Chicken', 'Quick Meal'],
    latitude: 5.266430598573402, 
    longitude: 103.16884703496062,
  ),
  Place(
    title: 'Seafood Kuala Ibai Bawah Jambatan',
    rating: 4.0,
    image: 'assets/Foods/food14.jpg',
    overview: 'A seafood restaurant with a view of the river.',
    description: 'Seafood Kuala Ibai Bawah Jambatan offers a unique dining experience with its riverside location. The menu features a variety of seafood dishes, served in a relaxed and scenic setting.',
    tags: ['Seafood', 'Riverside', 'Scenic', 'Relaxed', 'View'],
    latitude: 5.279223927940781, 
    longitude: 103.16887886749518,
  ),
  Place(
    title: 'Kedai Makan Kak Chik',
    rating: 4.4,
    image: 'assets/Foods/food15.jpg',
    overview: 'A local eatery known for its delicious and affordable dishes.',
    description: 'Kedai Makan Kak Chik is a favorite among locals for its delicious and affordable dishes. The menu includes a variety of local favorites, served in a casual and friendly atmosphere.',
    tags: ['Local Eatery', 'Affordable', 'Casual', 'Friendly Atmosphere'],
    latitude: 5.266638716114563, 
    longitude: 103.18129691942576,
  ),
  Place(
    title: 'Kedai Makan Tepi Jalan',
    rating: 3.9,
    image: 'assets/Foods/food16.jpg',
    overview: 'A roadside eatery offering a variety of local dishes.',
    description: 'Kedai Makan Tepi Jalan offers a variety of local dishes, served in a casual and relaxed setting. The friendly service and tasty food make it a popular choice for a quick meal.',
    tags: ['Roadside', 'Local Dishes', 'Casual', 'Quick Meal'],
    latitude: 5.273107146198355, 
    longitude: 103.17646550002982,
  ),
  Place(
    title: 'AR Seafood - Ikan Bakar',
    rating: 4.2,
    image: 'assets/Foods/food17.jpg',
    overview: 'A seafood restaurant specializing in grilled fish.',
    description: 'AR Seafood - Ikan Bakar is known for its delicious grilled fish and seafood dishes. The casual atmosphere and flavorful food make it a great choice for seafood lovers.',
    tags: ['Seafood', 'Grilled Fish', 'Casual', 'Flavorful'],
    latitude: 5.2771998283240515, 
    longitude: 103.16800511352287,
  ),
  Place(
    title: 'WARONG ANOK MIE',
    rating: 4.4,
    image: 'assets/Foods/food18.jpg',
    overview: 'A local eatery offering a variety of traditional dishes.',
    description: 'WARONG ANOK MIE is a popular spot for traditional local dishes. The menu features a variety of flavorful and authentic options, served in a casual and friendly setting.',
    tags: ['Local Eatery', 'Traditional', 'Flavorful', 'Authentic', 'Friendly'],
    latitude: 5.269215396705665, 
    longitude: 103.17675395009402,
  ),
  Place(
    title: 'Wani Tomyam',
    rating: 3.9,
    image: 'assets/Foods/food19.jpg',
    overview: 'A restaurant offering a variety of Thai dishes.',
    description: 'Wani Tomyam brings the flavors of Thailand to Terengganu with its delicious Thai dishes. The menu includes a variety of options, from spicy soups to flavorful curries.',
    tags: ['Thai', 'Spicy', 'Soups', 'Curries'],
    latitude: 5.2557814560928655, 
    longitude: 103.18219404874262,
  ),
  Place(
    title: 'Zie Corner',
    rating: 3.9,
    image: 'assets/Foods/food20.jpg',
    overview: 'A casual eatery with a variety of local and international dishes.',
    description: 'Zie Corner offers a diverse menu with both local and international dishes. The casual atmosphere and tasty food make it a great spot for a relaxed meal.',
    tags: ['Casual', 'Local Dishes', 'International', 'Relaxed', 'Diverse Menu'],
    latitude: 5.325895484890396, 
    longitude: 103.13234150982412,
  ),
    ],
  ),
  PlaceCategory(
    category: 'Drinks',
    places: [
      Place(
    title: 'ZUS Coffee - Jalan Pejabat',
    rating: 4.0,
    image: 'assets/Drinks/drink1.jpg',
    overview: 'A refreshing cocktail made with lime, mint, and rum.',
    description: 'Our mojito is a perfect blend of fresh lime, mint, and white rum, topped with soda water. It\'s a refreshing drink that\'s perfect for a hot day.',
    tags: ['Cocktail', 'Lime', 'Mint', 'Refreshing', 'Rum'],
    latitude: 5.329620448153919, 
    longitude: 103.1426971232126,
  ),
  Place(
    title: 'ZUS Coffee - Paya Bunga Square',
    rating: 4.8,
    image: 'assets/Drinks/drink2.jpg',
    overview: 'A classic homemade lemonade with fresh lemons and sugar.',
    description: 'Our lemonade is made with fresh lemons and just the right amount of sugar for a perfect balance of tart and sweet. It\'s a refreshing drink for any occasion.',
    tags: ['Lemonade', 'Fresh Lemons', 'Sweet', 'Refreshing'],
    latitude: 5.331026615558011, 
    longitude: 103.1367547237107,
  ),
  Place(
    title: 'ZUS Coffee - KTCC Mall',
    rating: 4.4,
    image: 'assets/Drinks/drink3.jpg',
    overview: 'A strong and rich shot of espresso coffee.',
    description: 'Our espresso is made from high-quality coffee beans, freshly ground and brewed to perfection. It\'s a rich and bold coffee experience.',
    tags: ['Espresso', 'Rich', 'Bold', 'High-Quality'],
    latitude: 5.332815536240906, 
    longitude: 103.15072796194693,
  ),
  Place(
    title: 'Tealive MBKT',
    rating: 4.4,
    image: 'assets/Drinks/drink4.jpg',
    overview: 'A healthy fruit smoothie made with fresh berries and yogurt.',
    description: 'Our smoothie is a blend of fresh berries, yogurt, and a touch of honey. It\'s a healthy and delicious drink that\'s perfect for breakfast or a snack.',
    tags: ['Smoothie', 'Fresh Berries', 'Yogurt', 'Healthy', 'Delicious'],
    latitude: 5.332627378200106, 
    longitude: 103.13771009669382,
  ),
  Place(
    title: 'Tealive Dataran Panji',
    rating: 3.9,
    image: 'assets/Drinks/drink5.jpg',
    overview: 'A refreshing iced tea brewed with black tea and lemon.',
    description: 'Our iced tea is brewed with high-quality black tea leaves and a hint of lemon. It\'s a refreshing and cooling drink that\'s perfect for any time of day.',
    tags: ['Iced Tea', 'Black Tea', 'Lemon', 'Refreshing', 'Cooling'],
    latitude: 5.313911435407193, 
    longitude: 103.14488057151893,
  ),
  Place(
    title: 'Tealive KTCC Mall',
    rating: 4.0,
    image: 'assets/Drinks/drink6.jpg',
    overview: 'A classic cappuccino with rich espresso and steamed milk.',
    description: 'Our cappuccino is made with a rich shot of espresso, topped with steamed milk and a layer of frothy foam. It\'s a classic coffee drink that\'s perfect for any time of day.',
    tags: ['Cappuccino', 'Espresso', 'Steamed Milk', 'Frothy Foam'],
    latitude: 5.334247337797666, 
    longitude: 103.14987832097918
  ),
  Place(
    title: 'Tealive Paya Bunga Square',
    rating: 3.7,
    image: 'assets/Drinks/drink7.jpg',
    overview: 'A fresh-squeezed orange juice full of vitamin C.',
    description: 'Our orange juice is made from freshly squeezed oranges, packed with vitamin C and a burst of citrus flavor. It\'s a healthy and refreshing drink.',
    tags: ['Orange Juice', 'Vitamin C', 'Citrus', 'Healthy', 'Refreshing'],
    latitude: 5.330895833642301, 
    longitude: 103.13679356702762,
  ),
  Place(
    title: 'Chatime KTCC Mall',
    rating: 3.0,
    image: 'assets/Drinks/drink8.jpg',
    overview: 'A creamy milkshake made with vanilla ice cream and milk.',
    description: 'Our milkshake is a creamy blend of vanilla ice cream and milk, topped with whipped cream and a cherry. It\'s a delicious treat that\'s perfect for dessert.',
    tags: ['Milkshake', 'Vanilla', 'Creamy', 'Dessert'],
    latitude: 5.334045084157873, 
    longitude: 103.14981753743379,
  ),
  Place(
    title: 'Coolblog Giant Hypermarket',
    rating: 4.0,
    image: 'assets/Drinks/drink9.jpg',
    overview: 'A mixed cocktail with a blend of fruit juices and spirits.',
    description: 'Our cocktail is a refreshing mix of fruit juices and spirits, served over ice and garnished with fresh fruit. It\'s a perfect drink for a night out.',
    tags: ['Cocktail', 'Fruit Juices', 'Spirits', 'Refreshing', 'Night Out'],
    latitude: 5.3111479846362775, 
    longitude: 103.13132038098843,
  ),
  Place(
    title: 'Coolblog KTCC Mall',
    rating: 3.0,
    image: 'assets/Drinks/drink10.jpg',
    overview: 'A rich and creamy hot chocolate made with real cocoa.',
    description: 'Our hot chocolate is made with real cocoa and steamed milk, topped with whipped cream and a sprinkle of chocolate shavings. It\'s a warm and comforting drink.',
    tags: ['Hot Chocolate', 'Cocoa', 'Creamy', 'Warm', 'Comforting'],
    latitude: 5.333330265722111, 
    longitude: 103.15085283071501,
  ),
  Place(
    title: 'Coolblog PAYA BUNGA SQUARE',
    rating: 3.3,
    image: 'assets/Drinks/drink11.jpg',
    overview: 'A smooth and creamy latte with espresso and steamed milk.',
    description: 'Our latte is made with a rich shot of espresso and steamed milk, topped with a thin layer of foam. It\'s a smooth and creamy coffee drink.',
    tags: ['Latte', 'Espresso', 'Steamed Milk', 'Creamy', 'Smooth'],
    latitude: 5.331235706784766, 
    longitude: 103.13737672146772,
  ),
  Place(
    title: 'Oldtown White Coffee',
    rating: 4.0,
    image: 'assets/Drinks/drink12.jpg',
    overview: 'A tropical pina colada with pineapple, coconut, and rum.',
    description: 'Our pina colada is a tropical blend of pineapple juice, coconut cream, and white rum. It\'s a refreshing drink that\'s perfect for a summer day.',
    tags: ['Pina Colada', 'Pineapple', 'Coconut', 'Rum', 'Tropical'],
    latitude: 5.328721787666496,   
    longitude: 103.1359529070977,
  ),
  Place(
    title: 'Kalut Cafe',
    rating: 3.9,
    image: 'assets/Drinks/drink13.jpg',
    overview: 'A classic margarita with tequila, lime juice, and triple sec.',
    description: 'Our margarita is a classic blend of tequila, lime juice, and triple sec, served over ice with a salted rim. It\'s a refreshing and tangy drink.',
    tags: ['Margarita', 'Tequila', 'Lime', 'Triple Sec', 'Tangy'],
    latitude: 5.402969349793592, 
    longitude: 103.07150666379674,
  ),
  Place(
    title: 'The Cendol Champion and Homestay',
    rating: 4.2,
    image: 'assets/Drinks/drink14.jpg',
    overview: 'A spiced chai latte made with black tea, spices, and steamed milk.',
    description: 'Our chai latte is a blend of black tea, spices, and steamed milk, topped with a sprinkle of cinnamon. It\'s a warm and comforting drink with a hint of spice.',
    tags: ['Chai Latte', 'Black Tea', 'Spices', 'Steamed Milk', 'Warm'],
    latitude: 5.418728659573101, 
    longitude: 103.06407761352342,
  ),
  Place(
    title: 'Air Buah Pak San',
    rating: 4.0,
    image: 'assets/Drinks/drink15.jpg',
    overview: 'A warm apple cider spiced with cinnamon and cloves.',
    description: 'Our apple cider is made with fresh apples, cinnamon, and cloves, served warm for a comforting and spicy drink. It\'s perfect for a cozy evening.',
    tags: ['Apple Cider', 'Cinnamon', 'Cloves', 'Warm', 'Comforting'],
    latitude: 5.36180521355259, 
    longitude: 103.11767579448173,
  ),
  Place(
    title: 'Beruang Cafe',
    rating: 3.8,
    image: 'assets/Drinks/drink16.jpg',
    overview: 'A refreshing mint julep with bourbon, mint, and sugar.',
    description: 'Our mint julep is a refreshing blend of bourbon, fresh mint, and sugar, served over crushed ice. It\'s a classic Southern cocktail.',
    tags: ['Mint Julep', 'Bourbon', 'Mint', 'Sugar', 'Refreshing'],
    latitude: 5.314074149173436, 
    longitude: 103.14286453496082,
  ),
  Place(
    title: 'Knock Knock',
    rating: 4.8,
    image: 'assets/Drinks/drink17.jpg',
    overview: 'A creamy matcha latte made with green tea powder and steamed milk.',
    description: 'Our matcha latte is made with high-quality green tea powder and steamed milk, topped with a layer of foam. It\'s a healthy and delicious drink.',
    tags: ['Matcha Latte', 'Green Tea', 'Steamed Milk', 'Creamy', 'Healthy'],
    latitude: 5.334863494832203, 
    longitude: 103.1347207717411,
  ),
  Place(
    title: 'Coffeekicx',
    rating: 4.8,
    image: 'assets/Drinks/drink18.jpg',
    overview: 'A spicy Bloody Mary with vodka, tomato juice, and spices.',
    description: 'Our Bloody Mary is a spicy blend of vodka, tomato juice, and a mix of spices, served with a celery stick and a lemon wedge. It\'s a bold and flavorful drink.',
    tags: ['Bloody Mary', 'Vodka', 'Tomato Juice', 'Spices', 'Spicy'],
    latitude: 5.3228146900975, 
    longitude: 103.15324517359053,
  ),
  Place(
    title: 'The Bencoolen Coffee',
    rating: 4.5,
    image: 'assets/Drinks/drink19.jpg',
    overview: 'A refreshing iced coffee made with cold brew and milk.',
    description: 'Our iced coffee is made with smooth cold brew coffee and a splash of milk, served over ice. It\'s a refreshing pick-me-up for any time of day.',
    tags: ['Iced Coffee', 'Cold Brew', 'Milk', 'Refreshing'],
    latitude: 5.330572231226996, 
    longitude: 103.13760758098846,
  ),
  Place(
    title: 'Brew Lab Coffee Specialist',
    rating: 4.9,
    image: 'assets/Drinks/drink20.jpg',
    overview: 'A healthy green smoothie made with spinach, banana, and almond milk.',
    description: 'Our green smoothie is a blend of fresh spinach, banana, and almond milk, sweetened with a touch of honey. It\'s a nutritious and delicious drink.',
    tags: ['Green Smoothie', 'Spinach', 'Espresso', 'Almond Milk', 'Nutritious'],
    latitude: 5.329434661362875, 
    longitude: 103.13512196564595,
  ),
    ],
  ),
];
List<Place> searchPlaces(String query) {
  List<Place> results = [];
  for (var category in placeCategories) {
    for (var place in category.places) {
      if (place.title.toLowerCase().contains(query.toLowerCase())) {
        results.add(place);
      }
    }
  }
  return results;
}
